name: covid_weapon
description: A new Flutter application.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_charts: ^18.4.34
  syncfusion_flutter_gauges: ^18.4.34
  get_it: ^5.0.3
  auto_route: ^0.6.9
  dio: ^3.0.10
  path_provider: ^1.6.24
  freezed_annotation: ^0.12.0
  mobx: ^1.2.1+4
  provider: ^4.3.2+3
  flutter_mobx: ^1.1.0+2
  intl: ^0.16.1
  url_launcher: ^5.7.10

dev_dependencies:
  build_runner:
  auto_route_generator: ^0.6.10
  freezed: ^0.12.3
  mobx_codegen: ^1.1.2

flutter:

  uses-material-design: true

  assets:
    - images/background1.png
    - images/background2.jpg
    - images/background3.png
    - images/background-slice1.png
    - images/background-slice2.png
    - images/buymeacoffeebutton.png
    - images/ourworldindata.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
      - family: FontIcon
        fonts:
          - asset: fonts/FontIcon.ttf
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
