name: covid_weapon
description: A new Flutter application.

publish_to: 'none'


version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_charts: ^18.4.34
  syncfusion_flutter_gauges: ^18.4.34
  get_it: ^5.0.3
  auto_route: ^0.6.9
  dio: ^3.0.10
  path_provider: ^1.6.24
  freezed_annotation: ^0.12.0
  mobx: ^1.2.1+4
  provider: ^4.3.2+3
  flutter_mobx: ^1.1.0+2
  intl: ^0.16.1
  url_launcher: ^5.7.10

dev_dependencies:
  build_runner:
  auto_route_generator: ^0.6.10
  freezed: ^0.12.3
  mobx_codegen: ^1.1.2

flutter:

  uses-material-design: true

  assets:
    - images/background1.png
    - images/background2.jpg
    - images/background3.png
    - images/background-slice1.png
    - images/background-slice2.png
    - images/buymeacoffeebutton.png
    - images/ourworldindata.jpg
    - assets/vaccines.json

  fonts:
      - family: FontIcon
        fonts:
          - asset: fonts/FontIcon.ttf
      - family: Quantico
        fonts:
          - asset: fonts/Quantico-Regular.otf
          - asset: fonts/Quantico-Italic.otf
          - asset: fonts/Quantico-Bold.otf
          - asset: fonts/Quantico-BoldItalic.otf
