/// Flutter icons FontIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FontIcon
///      fonts:
///       - asset: fonts/FontIcon.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class FontIcon {
  FontIcon._();

  static const _kFontFam = 'FontIcon';
  static const String _kFontPkg = null;

  static const IconData vaccine = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kettlebell = IconData(0xea14, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
